#!/usr/bin/env bash

# Run Storybook for a given project. Not intended to be executed directly, prefer `npm run storybook`.

set -euo pipefail

project="${1:-}"

if [ -z "$project" ]; then
	echo 'error: must specify the name of a project'
fi

npx nx run "$project":storybook
